### ISSUE TITLE
0.7 removed from grails plugin repo

### ISSUE THREAD

**Issue by OptimusPrimeLogan** [goeh/grails-qrcode#21]
Ref: https://repo.grails.org/grails/core/org/grails/plugins/qrcode/

**Comment by OptimusPrimeLogan** [comment]
@goeh

**Comment by goeh** [comment]
I'm confused. I cannot find any Grails 2.x plugins there.

**Comment by goeh** [comment]
Here is the Grails 2.x repo https://repo.grails.org/grails/plugins/org/grails/plugins/qrcode/

**Comment by OptimusPrimeLogan** [comment]
Thanks for your help, apologies for the delay in response.
